name: Pull Request
on:
  push:
    branches:
      - main


jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - run: cat test.sh
      - run: echo abc >> test.sh
      - name: Save files to workspace
        uses: actions/upload-artifact@v2
        with:
          name: my-workspace
          path: ./
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v2
        with:
          name: my-workspace
      - run: cat test.sh

