name: Pull Request
on:
  push:
    branches:
      - main


jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - run: cat test.sh
      - run: echo abc >> test.sh
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - run: cat test.sh

